TARGET = iphone:clang:latest:7.0
INSTALL_TARGET_PROCESSES = swiftapp

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = swiftapp

swiftapp_FILES = AppDelegate.swift RootViewController.swift
swiftapp_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
